language: node_js
node_js:
  - "0.11"
  - "0.10"
before_install:
  - "sudo apt-get update"
#  - "sudo apt-get install -y gcc g++"
#  - "sudo apt-get install -y gcc-multilib g++-multilib"
  - "sudo apt-get install -y g++-4.6-multilib gcc-4.6-multilib lib32gcc1 lib32stdc++6 libc-bin libc-dev-bin libc6 libc6-dev libc6-dev-i386 libc6-i386"
  - "sudo apt-get install -y libgtk2.0-0:i386 libgconf2-4:i386 libnss3:i386 libasound2-dev:i386 libxtst6:i386 libcap2:i386"