language: node_js
node_js:
  - "0.11"
  # disabled because of CERT_UNTRUSTED error while running node-gyp
  #- "0.10"
before_install:
  - "sudo apt-get update"
  # we need these packages to run atom-shell
  - "sudo apt-get install -y libgtk2.0-0:i386 libgconf2-4:i386 libnss3:i386 libasound2-dev:i386 libxtst6:i386 libcap2:i386"
  # we need these packages to compile for ia32
  # also, we need to install these last for some reason
  - "sudo apt-get install -y gcc-multilib g++-multilib"